
package exchange.v2007sp3.ws.client.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ExchangeServices", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", wsdlLocation = "file:Services.wsdl")
public class ExchangeServices
    extends Service
{

    private final static URL EXCHANGESERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(exchange.v2007sp3.ws.client.impl.ExchangeServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = exchange.v2007sp3.ws.client.impl.ExchangeServices.class.getResource(".");
            url = new URL(baseUrl, "file:Services.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:Services.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXCHANGESERVICES_WSDL_LOCATION = url;
    }

    public ExchangeServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeServices() {
        super(EXCHANGESERVICES_WSDL_LOCATION, new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeServices"));
    }

    /**
     * 
     * @return
     *     returns ExchangeServicePortType
     */
    @WebEndpoint(name = "ExchangeServicePort")
    public ExchangeServicePortType getExchangeServicePort() {
        return super.getPort(new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeServicePort"), ExchangeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeServicePortType
     */
    @WebEndpoint(name = "ExchangeServicePort")
    public ExchangeServicePortType getExchangeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeServicePort"), ExchangeServicePortType.class, features);
    }

}
