
package exchange.v2007sp3.ws.client.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ExchangeServicePortType", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExchangeServicePortType {


    /**
     * 
     * @param resolveNamesResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "ResolveNames", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ResolveNames")
    public void resolveNames(
        @WebParam(name = "ResolveNames", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ResolveNamesType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "ResolveNamesResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ResolveNamesResult")
        Holder<ResolveNamesResponseType> resolveNamesResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param expandDLResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "ExpandDL", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ExpandDL")
    public void expandDL(
        @WebParam(name = "ExpandDL", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ExpandDLType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "ExpandDLResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ExpandDLResult")
        Holder<ExpandDLResponseType> expandDLResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param findFolderResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "FindFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindFolder")
    public void findFolder(
        @WebParam(name = "FindFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "FindFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindFolderResult")
        Holder<FindFolderResponseType> findFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param findItemResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "FindItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindItem")
    public void findItem(
        @WebParam(name = "FindItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "FindItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindItemResult")
        Holder<FindItemResponseType> findItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getFolderResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "GetFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetFolder")
    public void getFolder(
        @WebParam(name = "GetFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "GetFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetFolderResult")
        Holder<GetFolderResponseType> getFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param convertIdResult
     * @param requestVersion
     */
    @WebMethod(operationName = "ConvertId", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ConvertId")
    public void convertId(
        @WebParam(name = "ConvertId", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ConvertIdType request,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "ConvertIdResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ConvertIdResult")
        Holder<ConvertIdResponseType> convertIdResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param createFolderResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "CreateFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateFolder")
    public void createFolder(
        @WebParam(name = "CreateFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "CreateFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateFolderResult")
        Holder<CreateFolderResponseType> createFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param deleteFolderResult
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "DeleteFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteFolder")
    public void deleteFolder(
        @WebParam(name = "DeleteFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "DeleteFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteFolderResult")
        Holder<DeleteFolderResponseType> deleteFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param updateFolderResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "UpdateFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateFolder")
    public void updateFolder(
        @WebParam(name = "UpdateFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "UpdateFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateFolderResult")
        Holder<UpdateFolderResponseType> updateFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     * @param moveFolderResult
     */
    @WebMethod(operationName = "MoveFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/MoveFolder")
    public void moveFolder(
        @WebParam(name = "MoveFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        MoveFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "MoveFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "MoveFolderResult")
        Holder<MoveFolderResponseType> moveFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param copyFolderResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "CopyFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CopyFolder")
    public void copyFolder(
        @WebParam(name = "CopyFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CopyFolderType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "CopyFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CopyFolderResult")
        Holder<CopyFolderResponseType> copyFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param subscribeResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "Subscribe", action = "http://schemas.microsoft.com/exchange/services/2006/messages/Subscribe")
    public void subscribe(
        @WebParam(name = "Subscribe", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SubscribeType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "SubscribeResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SubscribeResult")
        Holder<SubscribeResponseType> subscribeResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param unsubscribeResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "Unsubscribe", action = "http://schemas.microsoft.com/exchange/services/2006/messages/Unsubscribe")
    public void unsubscribe(
        @WebParam(name = "Unsubscribe", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UnsubscribeType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "UnsubscribeResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UnsubscribeResult")
        Holder<UnsubscribeResponseType> unsubscribeResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getEventsResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "GetEvents", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetEvents")
    public void getEvents(
        @WebParam(name = "GetEvents", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetEventsType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "GetEventsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetEventsResult")
        Holder<GetEventsResponseType> getEventsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     * @param syncFolderHierarchyResult
     */
    @WebMethod(operationName = "SyncFolderHierarchy", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderHierarchy")
    public void syncFolderHierarchy(
        @WebParam(name = "SyncFolderHierarchy", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SyncFolderHierarchyType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "SyncFolderHierarchyResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SyncFolderHierarchyResult")
        Holder<SyncFolderHierarchyResponseType> syncFolderHierarchyResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param syncFolderItemsResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "SyncFolderItems", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderItems")
    public void syncFolderItems(
        @WebParam(name = "SyncFolderItems", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SyncFolderItemsType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "SyncFolderItemsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SyncFolderItemsResult")
        Holder<SyncFolderItemsResponseType> syncFolderItemsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getItemResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "GetItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetItem")
    public void getItem(
        @WebParam(name = "GetItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "GetItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetItemResult")
        Holder<GetItemResponseType> getItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param timeZoneContext
     * @param request
     * @param serverVersion
     * @param createItemResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "CreateItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateItem")
    public void createItem(
        @WebParam(name = "CreateItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "TimeZoneContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "TimeZoneContext")
        TimeZoneContextType timeZoneContext,
        @WebParam(name = "CreateItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateItemResult")
        Holder<CreateItemResponseType> createItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     * @param deleteItemResult
     */
    @WebMethod(operationName = "DeleteItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteItem")
    public void deleteItem(
        @WebParam(name = "DeleteItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "DeleteItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteItemResult")
        Holder<DeleteItemResponseType> deleteItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param timeZoneContext
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     * @param updateItemResult
     */
    @WebMethod(operationName = "UpdateItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateItem")
    public void updateItem(
        @WebParam(name = "UpdateItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "TimeZoneContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "TimeZoneContext")
        TimeZoneContextType timeZoneContext,
        @WebParam(name = "UpdateItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateItemResult")
        Holder<UpdateItemResponseType> updateItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param sendItemResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "SendItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SendItem")
    public void sendItem(
        @WebParam(name = "SendItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SendItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "SendItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SendItemResult")
        Holder<SendItemResponseType> sendItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param moveItemResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "MoveItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/MoveItem")
    public void moveItem(
        @WebParam(name = "MoveItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        MoveItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "MoveItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "MoveItemResult")
        Holder<MoveItemResponseType> moveItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param copyItemResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "CopyItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CopyItem")
    public void copyItem(
        @WebParam(name = "CopyItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CopyItemType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "CopyItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CopyItemResult")
        Holder<CopyItemResponseType> copyItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param createAttachmentResult
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "CreateAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateAttachment")
    public void createAttachment(
        @WebParam(name = "CreateAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateAttachmentType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "CreateAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateAttachmentResult")
        Holder<CreateAttachmentResponseType> createAttachmentResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     * @param deleteAttachmentResult
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteAttachment")
    public void deleteAttachment(
        @WebParam(name = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteAttachmentType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteAttachmentResult")
        Holder<DeleteAttachmentResponseType> deleteAttachmentResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getAttachmentResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "GetAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetAttachment")
    public void getAttachment(
        @WebParam(name = "GetAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetAttachmentType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "GetAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetAttachmentResult")
        Holder<GetAttachmentResponseType> getAttachmentResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param createManagedFolderResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "CreateManagedFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateManagedFolder")
    public void createManagedFolder(
        @WebParam(name = "CreateManagedFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateManagedFolderRequestType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "CreateManagedFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateManagedFolderResult")
        Holder<CreateManagedFolderResponseType> createManagedFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getDelegateResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "GetDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetDelegate")
    public void getDelegate(
        @WebParam(name = "GetDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetDelegateType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "GetDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetDelegateResult")
        Holder<GetDelegateResponseMessageType> getDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     * @param addDelegateResult
     */
    @WebMethod(operationName = "AddDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/AddDelegate")
    public void addDelegate(
        @WebParam(name = "AddDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        AddDelegateType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "AddDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "AddDelegateResult")
        Holder<AddDelegateResponseMessageType> addDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param removeDelegateResult
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "RemoveDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/RemoveDelegate")
    public void removeDelegate(
        @WebParam(name = "RemoveDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        RemoveDelegateType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "RemoveDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "RemoveDelegateResult")
        Holder<RemoveDelegateResponseMessageType> removeDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param updateDelegateResult
     * @param request
     * @param serverVersion
     * @param impersonation
     * @param requestVersion
     * @param mailboxCulture
     * @param s2SAuth
     */
    @WebMethod(operationName = "UpdateDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateDelegate")
    public void updateDelegate(
        @WebParam(name = "UpdateDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateDelegateType request,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "S2SAuth")
        SerializedSecurityContextType s2SAuth,
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @WebParam(name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "MailboxCulture")
        String mailboxCulture,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "UpdateDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateDelegateResult")
        Holder<UpdateDelegateResponseMessageType> updateDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getUserAvailabilityRequest
     * @param serializedSecurityContext
     * @param serverVersion
     * @param impersonation
     * @param getUserAvailabilityResult
     * @param proxyRequestTypeHeader
     */
    @WebMethod(operationName = "GetUserAvailability", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserAvailability")
    public void getUserAvailability(
        @WebParam(name = "GetUserAvailabilityRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "GetUserAvailabilityRequest")
        GetUserAvailabilityRequestType getUserAvailabilityRequest,
        @WebParam(name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "SerializedSecurityContext")
        SerializedSecurityContextType serializedSecurityContext,
        @WebParam(name = "ProxyRequestTypeHeader", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "ProxyRequestTypeHeader")
        AvailabilityProxyRequestType proxyRequestTypeHeader,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "GetUserAvailabilityResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetUserAvailabilityResult")
        Holder<GetUserAvailabilityResponseType> getUserAvailabilityResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getUserOofSettingsResult
     * @param serverVersion
     * @param impersonation
     * @param getUserOofSettingsRequest
     */
    @WebMethod(operationName = "GetUserOofSettings", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserOofSettings")
    public void getUserOofSettings(
        @WebParam(name = "GetUserOofSettingsRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "GetUserOofSettingsRequest")
        GetUserOofSettingsRequest getUserOofSettingsRequest,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "GetUserOofSettingsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetUserOofSettingsResult")
        Holder<GetUserOofSettingsResponse> getUserOofSettingsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param setUserOofSettingsRequest
     * @param serverVersion
     * @param impersonation
     * @param setUserOofSettingsResult
     */
    @WebMethod(operationName = "SetUserOofSettings", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SetUserOofSettings")
    public void setUserOofSettings(
        @WebParam(name = "SetUserOofSettingsRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "SetUserOofSettingsRequest")
        SetUserOofSettingsRequest setUserOofSettingsRequest,
        @WebParam(name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", partName = "Impersonation")
        ExchangeImpersonationType impersonation,
        @WebParam(name = "SetUserOofSettingsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SetUserOofSettingsResult")
        Holder<SetUserOofSettingsResponse> setUserOofSettingsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);
    
    
    /**
     * Additional methods
     */
    
    @WebMethod(operationName = "FindItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindItem")
    public void findItem(
        @WebParam(name = "FindItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindItemType request,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "FindItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindItemResult")
        Holder<FindItemResponseType> findItemResult);
    
    @WebMethod(operationName = "GetItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetItem")
    public void getItem(
        @WebParam(name = "GetItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetItemType request,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "GetItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetItemResult")
        Holder<GetItemResponseType> getItemResult);
    
    @WebMethod(operationName = "DeleteItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteItem")
    public void deleteItem(
        @WebParam(name = "DeleteItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteItemType request,
        @WebParam(name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, partName = "RequestVersion")
        RequestServerVersion requestVersion,
        @WebParam(name = "DeleteItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteItemResult")
        Holder<DeleteItemResponseType> deleteItemResult);

}
