#!/bin/bash
if [ ! -d /home/mlzboy/b2c2/shared/db ]; then
mkdir -p mbox;
fi;
for i in 01 02 03 04 05 06 07 08 09 10 11 12
do
curl http://mail-archives.apache.org/mod_mbox/hadoop-common-dev/2012${i}.mbox > mbox/hadoop-common-dev-2012${i}.mbox
done